export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SELECTED_ACCOUNT = "SELECTED_ACCOUNT";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";

export const INCOME_AND_EXPENSE = "INCOME_AND_EXPENSE";

export const TRY_SIGNUP = "TRY_SIGNUP";
export const TRY_LOGIN = "TRY_LOGIN";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";